### ISSUE TITLE
FastDFSClient是否线程安全？

### ISSUE THREAD

**Issue by SherlockLiang** [quhailong/NetworkDisk_Storage#2]
FastDFSClient中无论是上传还是下载文件，都会重新把storageClient new一个出来。而且方法没有任何阻塞，是否在多线程环境下线程安全？

**Comment by quhailong** [comment]
线程不安全吧，用完就关闭了

**Comment by quhailong** [comment]
> FastDFSClient中无论是上传还是下载文件，都会重新把storageClient new一个出来。而且方法没有任何阻塞，是否在多线程环境下线程安全？

线程不安全吧，用完就关闭了
