### ISSUE TITLE
文档能不能齐全一点呢

### ISSUE THREAD

**Issue by jujube-framework** [quhailong/NetworkDisk_Storage#6]
1、文档需要完善，比如项目启动顺序和sql文件位置
2、最好有一个聚合pom.xml，就可以一键导入到IDE了

**Comment by quhailong** [comment]
> 1、文档需要完善，比如项目启动顺序和sql文件位置
> 2、最好有一个聚合pom.xml，就可以一键导入到IDE了

1、pan,sql就是sql文件，在外面放着清清楚楚，根据模块说明，你应该知道先启动哪个
2、pan-parent模块就是总的pom管理
